"""Install the AP-AUTH-41 v6 + AP-AUTH-42 NEW pre-commit hook into .git/hooks.

The pre-commit framework (https://pre-commit.com) is NOT a project dependency
in this repo as of L5-A. To get the same enforcement without adding a new
dependency, this script writes a plain `.git/hooks/pre-commit` shell script
that calls the two validators on staged `docs/**/*.md` files.

If the pre-commit framework is later added, the parallel `.pre-commit-config.yaml`
in the repo root provides the same declarative wiring; `pre-commit install`
would supersede this script's output.

Run once after cloning OR creating a new worktree:
    python scripts/precommit/install_hook.py

Idempotent: re-running overwrites the hook with the same content.

Exit codes:
    0 = installed successfully
    1 = install failed (e.g., cannot resolve hooks path)
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

HOOK_BODY = '''#!/bin/sh
# AP-AUTH-41 v6 STRENGTHENED + AP-AUTH-42 NEW v6 pre-commit hook
# Generated by scripts/precommit/install_hook.py
# Build plan ref: claude/layer-5-build-plan @ 32cce8b ITEM 6
#
# Enforces:
#   - validate_dual_grep_in_verification.py (AP-AUTH-41 v6)
#   - validate_no_cumulative_arithmetic.py (AP-AUTH-42 NEW v6)
# on staged `docs/**/*.md` files.
#
# Bypass via `--no-verify` is a circle-of-fire offense per Strategic
# prompt §3 (4). If hook fires falsely, fix the validator + file
# AP register addition; do NOT bypass.

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

# Resolve Python interpreter — prefer project .venv over system Python.
if [ -x "$REPO_ROOT/.venv/Scripts/python.exe" ]; then
    PYTHON="$REPO_ROOT/.venv/Scripts/python.exe"
elif [ -x "$REPO_ROOT/.venv/bin/python" ]; then
    PYTHON="$REPO_ROOT/.venv/bin/python"
else
    PYTHON=python
fi

# List staged docs/**/*.md files (added/copied/modified/renamed).
STAGED=$(git diff --cached --name-only --diff-filter=ACMR -- 'docs/*.md' 'docs/**/*.md')

if [ -z "$STAGED" ]; then
    exit 0
fi

echo "[precommit] Validating staged docs/**/*.md files for AP-AUTH-41/42..."

# Run both validators; fail commit on any violation.
echo "$STAGED" | xargs "$PYTHON" "$REPO_ROOT/scripts/precommit/validate_dual_grep_in_verification.py" || {
    echo "[precommit] BLOCKED by AP-AUTH-41 v6 (dual-grep)." >&2
    exit 1
}

echo "$STAGED" | xargs "$PYTHON" "$REPO_ROOT/scripts/precommit/validate_no_cumulative_arithmetic.py" || {
    echo "[precommit] BLOCKED by AP-AUTH-42 NEW v6 (cumulative arithmetic)." >&2
    exit 1
}

echo "[precommit] OK"
exit 0
'''


def main() -> int:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        print(f"[install_hook] FAIL: cannot resolve git hooks path: {exc}",
              file=sys.stderr)
        return 1

    hooks_dir = Path(result.stdout.strip())
    if not hooks_dir.is_absolute():
        # `git rev-parse --git-path hooks` returns absolute path normally,
        # but be defensive in case it returns relative.
        hooks_dir = Path.cwd() / hooks_dir

    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "pre-commit"

    hook_path.write_text(HOOK_BODY, encoding="utf-8")

    # Make executable on Unix-like systems (no-op on Windows where Git Bash
    # honors the shebang regardless of file mode).
    try:
        os.chmod(hook_path, 0o755)
    except OSError as exc:
        print(f"[install_hook] WARN: cannot chmod {hook_path}: {exc}",
              file=sys.stderr)

    print(f"[install_hook] OK: installed pre-commit hook at {hook_path}")
    print("[install_hook] Coverage: docs/**/*.md")
    print("[install_hook] Validators: AP-AUTH-41 v6 dual-grep + "
          "AP-AUTH-42 NEW cumulative arithmetic.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
