#!/usr/bin/env python3
"""Train and freeze the 3-state Gaussian HMM regime classifier (v1).

Admin-only utility per ``LAYER_3_5_BUILD_SPEC.md`` §3.5A. Not part of
the ``macro_pipeline`` package; runnable as
``python scripts/train_hmm_v1.py``.

Outputs (atomically):

- ``data/cache/hmm/regime_3state_v1.pkl``       — pickled ``TrainedHmm``
- ``data/cache/hmm/regime_3state_v1.meta.json`` — sidecar metadata

The inference path (``macro_pipeline.regime.load_hmm``) loads these
artifacts and verifies the sidecar's ``data_sha256`` against the
recomputed pickle hash. The pickle is NEVER regenerated by inference
code; this script is the sole entry-point for re-creating it.

CLI:

    python scripts/train_hmm_v1.py [--force-overwrite] [--dry-run]

Returns:

    0  success (or dry-run with no diff)
    1  hmmlearn version mismatch
    2  existing artifact diverges from would-be artifact and
       --force-overwrite was not passed
    3  training matrix has < 100 obs (data drift)
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import pickle
import sys
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
import pandas as pd

# We rely on macro_pipeline for data access, dataclasses, and atomic
# write helpers — but the reverse import is forbidden.
HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from macro_pipeline.access import load_series  # noqa: E402
from macro_pipeline.cache import (  # noqa: E402
    write_pickle_atomic_with_meta,
)
from macro_pipeline.regime.hmm_states import (  # noqa: E402
    HMM_FEATURES,
    HMM_PICKLE_PATH,
    HMM_RANDOM_STATE,
    HMM_TRAINING_END,
    HMM_TRAINING_START,
    HMM_VERSION,
    TrainedHmm,
)

PICKLE_PROTOCOL = 4
SIDECAR_SCHEMA_VERSION = "1.0"
EXPECTED_HMMLEARN_VERSION = "0.3.3"
PICKLE_PATH = HMM_PICKLE_PATH
SIDECAR_PATH = PICKLE_PATH.with_suffix(".meta.json")


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _df_to_canonical_csv_bytes(df: pd.DataFrame) -> bytes:
    """Serialize df to a deterministic CSV (UTF-8, ISO dates, fixed
    float repr) suitable for sha256 hashing.

    Determinism contract: same df → same bytes regardless of pandas
    minor version (pinning index format + line terminator + float
    format here defends against pandas-side drift).
    """
    buf = io.StringIO()
    df.to_csv(
        buf,
        index=True,
        date_format="%Y-%m-%d",
        float_format="%.17g",  # full IEEE-754 round-trip
        lineterminator="\n",
    )
    return buf.getvalue().encode("utf-8")


def _series_to_canonical_csv_bytes(s: pd.Series) -> bytes:
    return _df_to_canonical_csv_bytes(s.to_frame())


def _build_monthly_features(end: pd.Timestamp) -> pd.DataFrame:
    """Build the monthly feature DataFrame ending at ``end`` (latest mode)."""
    monthly_frames: list[pd.Series] = []
    for sid in HMM_FEATURES:
        bundle = load_series(sid)
        s = bundle.data.dropna()
        if s.empty:
            raise SystemExit(
                f"FATAL: feature {sid!r} empty in latest cache; "
                "training cannot proceed."
            )
        monthly = s.resample("ME").last()
        monthly = monthly[monthly.index <= end]
        monthly.name = sid
        monthly_frames.append(monthly)
    df = pd.concat(monthly_frames, axis=1, sort=True).dropna()
    return df


def _fit_hmm(features: np.ndarray) -> object:
    """Fit a 3-state GaussianHMM."""
    from hmmlearn.hmm import GaussianHMM

    hmm = GaussianHMM(
        n_components=3,
        covariance_type="full",
        n_iter=200,
        tol=1e-4,
        random_state=HMM_RANDOM_STATE,
        verbose=False,
    )
    hmm.fit(features)
    return hmm


def _label_states_by_nber(
    states: np.ndarray, observation_dates: pd.DatetimeIndex,
) -> tuple[dict[int, str], dict[int, float], pd.Series]:
    """Map raw HMM state indices → expansion/late-cycle/recession.

    Returns the mapping, per-state NBER overlap, and the aligned NBER
    label series used (for sha hashing in the sidecar).
    """
    nber_bundle = load_series("NBER_REC_LABEL")
    nber = nber_bundle.data.dropna()
    nber_monthly = nber.resample("ME").last()
    aligned = nber_monthly.reindex(observation_dates).fillna(0.0).astype(float)
    aligned.name = "NBER_REC_LABEL"

    overlap: dict[int, float] = {}
    for state_idx in range(3):
        mask = states == state_idx
        if mask.sum() == 0:
            overlap[state_idx] = float("nan")
        else:
            overlap[state_idx] = float(aligned.values[mask].mean())

    finite = {k: v for k, v in overlap.items() if np.isfinite(v)}
    if len(finite) < 3:
        raise SystemExit(
            f"FATAL: empty HMM state during training; overlap={overlap}"
        )

    sorted_states = sorted(finite.items(), key=lambda kv: kv[1])
    state_to_label = {
        sorted_states[0][0]: "expansion",
        sorted_states[1][0]: "late-cycle",
        sorted_states[2][0]: "recession",
    }
    return state_to_label, overlap, aligned


def _check_hmmlearn_version() -> str:
    import hmmlearn

    actual = hmmlearn.__version__
    if actual != EXPECTED_HMMLEARN_VERSION:
        print(
            f"hmmlearn version mismatch: expected {EXPECTED_HMMLEARN_VERSION}, "
            f"got {actual}. The committed artifact is locked to the expected "
            f"version (sidecar `hmmlearn_version` field). Use a venv with "
            f"the locked version to reproduce.",
            file=sys.stderr,
        )
        raise SystemExit(1)
    return actual


def _build_artifact() -> tuple[bytes, dict, TrainedHmm]:
    """Train the HMM and produce the (pickle bytes, sidecar dict, bundle).

    The sidecar is finalised with `data_sha256` AFTER the caller writes
    the pickle (atomic write recomputes the hash). We do NOT include
    `data_sha256` in this dict; the writer adds it.
    """
    _check_hmmlearn_version()

    df = _build_monthly_features(end=HMM_TRAINING_END)
    df = df[df.index >= HMM_TRAINING_START]
    if len(df) < 100:
        print(
            f"FATAL: training matrix has {len(df)} obs (need >= 100). "
            "Data drift suspected; investigate.",
            file=sys.stderr,
        )
        raise SystemExit(3)

    raw = df.values.astype(float)
    feature_mean = raw.mean(axis=0)
    feature_std = raw.std(axis=0, ddof=1)
    feature_std[feature_std == 0] = 1.0
    standardized = (raw - feature_mean) / feature_std

    hmm = _fit_hmm(standardized)
    states = hmm.predict(standardized)
    state_to_label, overlap, aligned_nber = _label_states_by_nber(states, df.index)

    bundle = TrainedHmm(
        model_version=HMM_VERSION,
        feature_names=HMM_FEATURES,
        training_start=HMM_TRAINING_START,
        training_end=HMM_TRAINING_END,
        n_obs=len(df),
        feature_mean=feature_mean,
        feature_std=feature_std,
        state_to_label=state_to_label,
        nber_overlap_per_state=overlap,
        hmm=hmm,
    )

    pickle_bytes = pickle.dumps(bundle, protocol=PICKLE_PROTOCOL)

    feature_matrix_sha = _sha256_bytes(_df_to_canonical_csv_bytes(df))
    nber_label_sha = _sha256_bytes(_series_to_canonical_csv_bytes(aligned_nber))
    script_sha = _sha256_file(Path(__file__).resolve())

    import hmmlearn  # for version capture
    py_version = (
        f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    )

    sidecar = {
        "schema_version": SIDECAR_SCHEMA_VERSION,
        "model_version": "v1",
        "model_family": "GaussianHMM",
        "n_components": 3,
        "training_window_start": str(pd.Timestamp(HMM_TRAINING_START).strftime("%Y-%m")),
        "training_window_end": str(pd.Timestamp(HMM_TRAINING_END).strftime("%Y-%m")),
        "n_obs_train": int(len(df)),
        "feature_names": list(HMM_FEATURES),
        "feature_matrix_sha256": feature_matrix_sha,
        "nber_label_sha256": nber_label_sha,
        "state_to_label_mapping": {str(k): v for k, v in state_to_label.items()},
        "nber_overlap_per_state": {str(k): float(v) for k, v in overlap.items()},
        "hmmlearn_version": hmmlearn.__version__,
        "python_version": py_version,
        "pickle_protocol": PICKLE_PROTOCOL,
        "random_state": HMM_RANDOM_STATE,
        # data_sha256: filled by atomic writer
        "created_at_utc": datetime.now(UTC).isoformat(),
        "training_script_path": "scripts/train_hmm_v1.py",
        "training_script_sha256": script_sha,
    }
    return pickle_bytes, sidecar, bundle


def _existing_artifact_summary() -> tuple[str | None, dict | None]:
    if not PICKLE_PATH.exists():
        return None, None
    sha = _sha256_file(PICKLE_PATH)
    sc = None
    if SIDECAR_PATH.exists():
        try:
            sc = json.loads(SIDECAR_PATH.read_text())
        except json.JSONDecodeError:
            sc = None
    return sha, sc


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Train and freeze the 3-state Gaussian HMM v1 artifact."
    )
    parser.add_argument(
        "--force-overwrite",
        action="store_true",
        help="Overwrite the existing pickle even if its sha256 differs.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Compute the would-be artifact without writing. Reports "
        "would-be sha256 and diff vs existing committed artifact.",
    )
    args = parser.parse_args()

    pickle_bytes, sidecar, bundle = _build_artifact()
    would_be_sha = _sha256_bytes(pickle_bytes)

    existing_sha, existing_meta = _existing_artifact_summary()

    if args.dry_run:
        print(f"[dry-run] would-be pickle sha256: {would_be_sha}")
        if existing_sha is not None:
            same = "MATCH" if existing_sha == would_be_sha else "DIVERGE"
            print(f"[dry-run] existing  pickle sha256: {existing_sha}  ({same})")
            if existing_meta:
                print(
                    f"[dry-run] existing meta hmmlearn_version="
                    f"{existing_meta.get('hmmlearn_version')!r}  "
                    f"data_sha256={existing_meta.get('data_sha256')!r}"
                )
        else:
            print("[dry-run] no existing artifact")
        print(
            f"[dry-run] feature_matrix_sha256={sidecar['feature_matrix_sha256']}"
        )
        print(
            f"[dry-run] nber_label_sha256={sidecar['nber_label_sha256']}"
        )
        print(
            f"[dry-run] state_to_label_mapping="
            f"{sidecar['state_to_label_mapping']}"
        )
        print(
            f"[dry-run] nber_overlap_per_state="
            f"{sidecar['nber_overlap_per_state']}"
        )
        return 0

    if existing_sha is not None and existing_sha != would_be_sha and not args.force_overwrite:
        print(
            "FATAL: existing pickle sha256 differs from would-be artifact and "
            "--force-overwrite not passed. To replace the committed artifact, "
            "re-run with --force-overwrite.",
            file=sys.stderr,
        )
        print(f"  existing : {existing_sha}", file=sys.stderr)
        print(f"  would-be : {would_be_sha}", file=sys.stderr)
        return 2

    PICKLE_PATH.parent.mkdir(parents=True, exist_ok=True)
    write_pickle_atomic_with_meta(
        pickle_path=PICKLE_PATH,
        pickle_bytes=pickle_bytes,
        meta=sidecar,
    )

    final_sha = _sha256_file(PICKLE_PATH)
    print(f"Wrote {PICKLE_PATH} (sha256={final_sha})")
    print(f"Wrote {SIDECAR_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
