"""Layer 5b-C — Benjamini-Hochberg FDR gating across the L5 chain.

Spec ref: ChatGPT 5.5 Dim-3 OOS rigor mandate ("Multiple hypothesis
testing in the L5 chain... without FDR control, individual test
rejections cannot be trusted as 'significant'. Benjamini-Hochberg
(1995) procedure controlling false discovery rate at q=0.10 is the
standard institutional default") + build plan §3.1 L5b-C scope ("Apply
Benjamini-Hochberg FDR control across the multiple p-value surface
generated by L5 chain").

L5b-C (tag ``l5b-a-accept`` parent → ``l5b-b-accept`` parent →
``l5b-c-accept`` 2026-05-15): THIRD original OOS hardening sub-phase
post-kickoff. Closes the multiple-comparison burden across the L5
p-value family via the AP-AUTH-54 sixth-instance internal-
implementation variant pattern. AP-AUTH-54 envelope STAYS CLOSED at
4-instance characterization (KICK-4 heaviest / KICK-5 medium / KICK-6
lightest / L5b-A heavy); L5b-C is the 6th instance with three novel
sub-characteristics documented as within-envelope variants per
Strategic disposition 4: (a) NEW module file (``fdr_gating.py``); (b)
NEW gate (Gate 26); (c) NEW test file (``test_fdr_gating.py``).

Public API
----------
``FDRGatingDiagnostics``                  Frozen dataclass; 7 no-default fields + 5 invariants.
``compute_fdr_gating_for_l5_chain``       Aggregator over RidgeFitResult iterable; applies BH at q_threshold.

Internal helpers
----------------
``_benjamini_hochberg_qvalues``           Step-up monotone BH(1995) q-value computation.

Method (BH 1995 step-up monotone form)
--------------------------------------
Reference: Benjamini, Y., & Hochberg, Y. (1995) "Controlling the False
Discovery Rate: A Practical and Powerful Approach to Multiple Testing"
JRSS-B 57:289-300.

Given p-values ``p_1, p_2, ..., p_m`` and target FDR ``q`` (default
``0.10``):

  1. Sort p-values in ascending order: ``p_(1) <= p_(2) <= ... <= p_(m)``.
  2. Raw BH adjustment: ``raw_q_(i) = (m / i) * p_(i)``.
  3. Monotone correction (step-up form):
     ``q_(i) = min_{j >= i} raw_q_(j)`` enforces ascending
     monotonicity in sorted order. Computed efficiently via
     ``np.minimum.accumulate(raw_q[::-1])[::-1]``.
  4. Clip to ``[0, 1]`` per probability semantic.
  5. Unsort back to original input order so ``q_values[i]``
     corresponds to ``p_values[i]``.
  6. Reject hypothesis ``i`` iff ``q_values[i] <= q_threshold``.

Approach C honest dependence disclaimer (Strategic disposition 1)
-----------------------------------------------------------------
**BH(1995) controls FDR under independence or positive regression
dependence (PRDS).** Cross-horizon p-values in the L5 chain may
exhibit positive dependence due to common macro-regime drivers
(monetary policy, business cycle, market sentiment). BH-PRDS is the
appropriate institutional default for this scenario. **Benjamini-
Yekutieli (2001) "The Control of the False Discovery Rate in Multiple
Testing under Dependency" Ann Stat 29:1165-1188** provides FDR
control under arbitrary dependence (scaled by harmonic factor
``sum(1/i, i=1..m)``); BY is more conservative. BY is deferred as
L5b-residue; revisit if a future reviewer flag pushes precision on
the cross-horizon dependence structure.

This disclaimer mirrors:
* KICK-7 DMS source memo §4 honest-disclaimer pattern (institutional
  judgment within empirically-supported range, NOT fabricated
  precision)
* L5b-B simplified Wald disclaimer (pragmatic ``||delta_beta||^2 /
  pooled_var`` with chi-squared p-value, NOT full sandwich variance)

NaN handling (Strategic disposition 7)
--------------------------------------
The aggregator filters non-finite p-values via ``math.isfinite``
BEFORE applying BH. Rationale: existing L5 chain p-value-producing
modules return NaN under specific edge cases (e.g., 1Y/3Y horizons
where ``len(y_test) < 2`` at small test windows causes
``fit_ols_hac`` to return ``None`` → ``p_value_beta_hac = float("nan")``
per ``return_forecast.py`` lines around 1009-1011). Including NaN
in BH would propagate undefined behavior (``NaN <=`` comparisons
return False; q-value would be NaN; rejection set would be silently
corrupted).

Empirical cardinality at default fixture (n=480, seed=42, all
expanding-schedule horizons):

* 1Y/expanding: 0 finite ridge p-values + 1 break p-value = 1
* 3Y/expanding: 0 finite ridge p-values + 1 break p-value = 1
* 5Y/expanding: 10 finite ridge p-values + 1 break p-value = 11
* 10Y/expanding: 0 folds (underpowered guard fires)
* **Total m = 13 (not raw fold count 396)**

Future reviewer asking "why m=13 when there are 396 folds?" — the
answer is the NaN filter behavior at 1Y/3Y small test windows
(pre-existing characteristic; not L5b-C scope).

AP-AUTH-52 derivation
---------------------
``q_threshold`` default ``0.10`` per Benjamini-Hochberg (1995)
institutional recommendation + ChatGPT 5.5 Dim-3 OOS rigor mandate
("q=0.10 is the standard institutional default; lower q (0.05) for
higher-stakes inference"). NOT a magic number; cite literature in
commit message + this module docstring.

Gate 26 NEW (cross-cutting downstream-consumer)
------------------------------------------------
L5b-C introduces **Gate 26** as the first NEW gate since Gate 25
SEALED at L5-G. Gate 26 is cross-cutting (downstream of Gate 19-B1
Ridge + Gate 22 Brier + L5b-B structural break p-values) vs the
prior implementation-correctness gates which inspect a single
module's output. Strategic note documents this institutional
significance: first downstream-consumer gate in the family.
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Iterable, Literal, Optional

import numpy as np


@dataclass(frozen=True)
class FDRGatingDiagnostics:
    """Benjamini-Hochberg FDR gating diagnostics for the L5 chain.

    All seven fields no-default per AP-AUTH-53 step #3. The
    ``__post_init__`` validator enforces five invariants:
    (1) ``len(q_values) == len(raw_p_values)``,
    (2) ``len(test_labels) == len(raw_p_values)``,
    (3) ``n_tests == len(raw_p_values)``,
    (4) ``n_rejected == len(rejected_indices)``,
    (5) ``0.0 < q_threshold < 1.0`` (strict open interval).

    First multi-invariant ``__post_init__`` in the L5b sprint
    (mirrors L5b-B ``StructuralBreakDiagnostics`` consistency-invariant
    pattern; extends to five invariants here).

    Fields
    ------
    raw_p_values
        Input p-values fed into BH. Same order as ``test_labels``
        and ``q_values``. Already NaN-filtered by the aggregator.
    q_values
        BH-adjusted q-values (step-up monotone form). Same order as
        ``raw_p_values``. Each ``q_values[i]`` represents the smallest
        FDR level at which hypothesis ``i`` would be rejected.
    q_threshold
        Target FDR level. Must be in the strict open interval
        ``(0.0, 1.0)``. Default ``0.10`` per BH 1995 + ChatGPT 5.5
        Dim-3 institutional recommendation.
    n_tests
        Length of ``raw_p_values``. Stored explicitly to validate
        consistency at construction time.
    n_rejected
        Number of hypotheses rejected at ``q_threshold``. Equals
        ``len(rejected_indices)``.
    rejected_indices
        Tuple of int indices into ``raw_p_values`` where
        ``q_values[i] <= q_threshold``.
    test_labels
        Semantic labels for each p-value, used for downstream
        interpretability. Format (per aggregator convention):
        ``"<test_kind>/<horizon>/<schedule_type>/fold<fold_id>"``,
        e.g., ``"ridge_pvalue_beta_hac/5Y/expanding/fold9"`` or
        ``"break_pvalue/5Y/expanding/fold9"``.
    """

    raw_p_values: tuple[float, ...]
    q_values: tuple[float, ...]
    q_threshold: float
    n_tests: int
    n_rejected: int
    rejected_indices: tuple[int, ...]
    test_labels: tuple[str, ...]

    def __post_init__(self) -> None:
        # Invariant 1: q_values cardinality matches raw_p_values.
        if len(self.q_values) != len(self.raw_p_values):
            raise ValueError(
                f"len(q_values)={len(self.q_values)} must equal "
                f"len(raw_p_values)={len(self.raw_p_values)} "
                "(L5b-C consistency invariant 1)"
            )
        # Invariant 2: test_labels cardinality matches raw_p_values.
        if len(self.test_labels) != len(self.raw_p_values):
            raise ValueError(
                f"len(test_labels)={len(self.test_labels)} must equal "
                f"len(raw_p_values)={len(self.raw_p_values)} "
                "(L5b-C consistency invariant 2)"
            )
        # Invariant 3: n_tests == len(raw_p_values).
        if self.n_tests != len(self.raw_p_values):
            raise ValueError(
                f"n_tests={self.n_tests} must equal "
                f"len(raw_p_values)={len(self.raw_p_values)} "
                "(L5b-C consistency invariant 3)"
            )
        # Invariant 4: n_rejected == len(rejected_indices).
        if self.n_rejected != len(self.rejected_indices):
            raise ValueError(
                f"n_rejected={self.n_rejected} must equal "
                f"len(rejected_indices)={len(self.rejected_indices)} "
                "(L5b-C consistency invariant 4)"
            )
        # Invariant 5: q_threshold in strict open interval (0, 1).
        # Strict-open per Strategic Watch-point Phase 1: q_threshold = 0
        # would never reject anything; q_threshold = 1 would reject
        # everything (no FDR control). Both endpoints are degenerate.
        if not (0.0 < self.q_threshold < 1.0):
            raise ValueError(
                f"q_threshold={self.q_threshold} must be in (0.0, 1.0) "
                "strict open interval (L5b-C consistency invariant 5; "
                "BH 1995 endpoints degenerate)"
            )


def _benjamini_hochberg_qvalues(p_values: np.ndarray) -> np.ndarray:
    """Compute Benjamini-Hochberg (1995) step-up monotone q-values.

    Algorithm
    ---------
    Given ``p_values`` of length ``m``:

      1. Sort p-values ascending: ``p_(1) <= ... <= p_(m)``.
      2. Raw adjustment: ``raw_q_(i) = (m / i) * p_(i)``.
      3. Monotone correction: ``q_(i) = min_{j >= i} raw_q_(j)``.
         Computed as ``np.minimum.accumulate(raw_q[::-1])[::-1]``
         (reverse-cumulative-minimum trick).
      4. Clip to ``[0, 1]`` per probability semantic.
      5. Unsort back to original input order.

    Reference: Benjamini, Y., & Hochberg, Y. (1995) JRSS-B 57:289-300.

    Parameters
    ----------
    p_values
        1-D ``np.ndarray`` of finite p-values in ``[0, 1]``. NaN/inf
        values are NOT filtered by this helper; callers (e.g.,
        ``compute_fdr_gating_for_l5_chain``) must filter before
        invocation.

    Returns
    -------
    np.ndarray
        1-D q-values, same length and order as ``p_values``. Each
        ``q_values[i]`` is the smallest FDR level at which hypothesis
        ``i`` would be rejected under BH(1995).
    """
    p_arr = np.asarray(p_values, dtype=float)
    m = len(p_arr)
    if m == 0:
        return np.empty(0, dtype=float)
    # Sort indices ascending; ranks 1..m correspond to sorted positions.
    order = np.argsort(p_arr)
    sorted_p = p_arr[order]
    ranks = np.arange(1, m + 1, dtype=float)
    # Raw BH adjustment per sorted position.
    raw_q = (m / ranks) * sorted_p
    # Monotone correction: q_(i) = min over j >= i of raw_q_(j).
    # Implemented as reverse cumulative minimum then re-reverse.
    monotone_q = np.minimum.accumulate(raw_q[::-1])[::-1]
    # Clip to [0, 1] per probability semantic (raw_q can exceed 1 for
    # small p-values at small ranks; monotone correction can also
    # leave values > 1).
    monotone_q = np.clip(monotone_q, 0.0, 1.0)
    # Unsort to original input order.
    q_values = np.empty_like(monotone_q)
    q_values[order] = monotone_q
    return q_values


def _benjamini_yekutieli_qvalues(p_values: np.ndarray) -> np.ndarray:
    """Compute Benjamini-Yekutieli (2001) step-up monotone q-values
    for arbitrary dependence structure.

    Algorithm: ``q_BY = q_BH * c(m)`` where ``c(m) = sum(1/i for i in
    1..m)`` is the Benjamini-Yekutieli adjustment factor (typically
    ``c(m) ≈ ln(m) + γ`` for large m). Result is more conservative
    than BH (fewer rejections); appropriate when test dependence
    structure is unknown or known to be non-PRDS.

    Reference: Benjamini, Y., & Yekutieli, D. (2001) Annals of
    Statistics 29:1165-1188.

    L5b-F Phase 5 (F-M4a): closes Codex 5.5 + ChatGPT 5.5 R6 finding
    on BY method availability for general-dependence FDR control.

    Parameters
    ----------
    p_values
        1-D ``np.ndarray`` of finite p-values; callers must filter
        NaN before invocation (mirrors BH helper contract).

    Returns
    -------
    np.ndarray
        1-D q-values, same length and order as ``p_values``; each
        ``q_values[i]`` is the BY-adjusted q-value for hypothesis ``i``.
        Clipped to ``[0, 1]``.
    """
    p_arr = np.asarray(p_values, dtype=float)
    m = len(p_arr)
    if m == 0:
        return np.empty(0, dtype=float)
    # Compute BH q-values first.
    q_bh = _benjamini_hochberg_qvalues(p_arr)
    # BY adjustment factor c(m).
    c_m = float(np.sum(1.0 / np.arange(1, m + 1, dtype=float)))
    # Scale up; clip to [0, 1] since scaling can push BH q-values past 1.
    q_by = np.clip(q_bh * c_m, 0.0, 1.0)
    return q_by


def compute_fdr_gating_for_l5_chain(
    ridge_fits: Iterable["object"],
    q_threshold: float = 0.10,
    *,
    method: Literal["BH", "BY"] = "BH",
    family_id: Optional[str] = None,
) -> FDRGatingDiagnostics:
    """Aggregate p-values from the L5 chain and apply BH(1995) FDR
    control at ``q_threshold``.

    Collects two p-value families per ``RidgeFitResult`` in
    ``ridge_fits``:

      1. ``p_value_beta_hac`` (forecast-vs-realized univariate
         calibration regression slope; KICK-6 institutional label
         ``"forecast_vs_realized"``)
      2. ``structural_break_diagnostics.break_test_p_value``
         (when ``structural_break_diagnostics is not None``;
         L5b-B final-fold-only invocation)

    NaN filter (Strategic disposition 7): non-finite p-values are
    skipped via ``math.isfinite``. Rationale: 1Y/3Y horizons at small
    test windows produce NaN ``p_value_beta_hac`` due to
    ``fit_ols_hac`` returning None when ``len(y_test) < 2``. Without
    the filter, BH would propagate NaN and silently corrupt the
    rejection set.

    Semantic labels: each accepted p-value is tagged with a stable
    label of the form
    ``"<test_kind>/<horizon>/<schedule_type>/fold<fold_id>"`` for
    downstream interpretability of the rejection set. Examples:

    - ``"ridge_pvalue_beta_hac/5Y/expanding/fold9"``
    - ``"break_pvalue/5Y/expanding/fold9"``

    AP-AUTH-52 ``q_threshold`` derivation: default ``0.10`` per BH
    1995 + ChatGPT 5.5 Dim-3 mandate ("q=0.10 is the standard
    institutional default; lower q (0.05) for higher-stakes
    inference"). NOT a magic number.

    Parameters
    ----------
    ridge_fits
        Iterable of ``RidgeFitResult`` objects (post-L5b-B). Each
        contributes 0-2 finite p-values to the aggregation.
    q_threshold
        Target FDR level in the strict open interval ``(0.0, 1.0)``.
        Default ``0.10``.

    Returns
    -------
    FDRGatingDiagnostics
        Populated with all collected finite p-values, BH-adjusted
        q-values, rejection set at ``q_threshold``, and semantic
        labels. Empty-input case returns valid diagnostics with
        ``n_tests=0`` (degenerate-but-valid; ``q_threshold`` invariant
        still enforced).
    """
    # L5b-F Phase 5 (F-M4a) — validate method + family_id pairing.
    # BY method requires explicit family_id (non-None) per Strategic
    # disposition on R6 finding (multiple-comparison families must be
    # explicit at call site when applying general-dependence control).
    if method == "BY" and family_id is None:
        raise ValueError(
            "family_id is required when method='BY' "
            "(L5b-F Phase 5 F-M4a; general-dependence FDR control "
            "requires explicit family demarcation per Benjamini-"
            "Yekutieli 2001 Section 4)"
        )
    if method not in ("BH", "BY"):
        raise ValueError(
            f"method={method!r} must be 'BH' or 'BY' "
            "(L5b-F Phase 5 F-M4a tri-state taxonomy)"
        )

    raw_p_values: list[float] = []
    test_labels: list[str] = []

    for fit in ridge_fits:
        # (1) Ridge forecast-vs-realized p-value (KICK-6 label).
        p_ridge = getattr(fit, "p_value_beta_hac", None)
        if p_ridge is not None and math.isfinite(float(p_ridge)):
            raw_p_values.append(float(p_ridge))
            test_labels.append(
                f"ridge_pvalue_beta_hac/"
                f"{fit.horizon}/{fit.schedule_type}/fold{fit.fold_id}"
            )
        # (2) Structural break p-value (L5b-B final-fold-only).
        sb_diag = getattr(fit, "structural_break_diagnostics", None)
        if sb_diag is not None:
            p_break = getattr(sb_diag, "break_test_p_value", None)
            if p_break is not None and math.isfinite(float(p_break)):
                raw_p_values.append(float(p_break))
                test_labels.append(
                    f"break_pvalue/"
                    f"{fit.horizon}/{fit.schedule_type}/fold{fit.fold_id}"
                )

    if not raw_p_values:
        # Degenerate empty-input case (no finite p-values found).
        # Return valid diagnostics with m=0; q_threshold invariant
        # still enforced per __post_init__.
        return FDRGatingDiagnostics(
            raw_p_values=(),
            q_values=(),
            q_threshold=q_threshold,
            n_tests=0,
            n_rejected=0,
            rejected_indices=(),
            test_labels=(),
        )

    p_arr = np.asarray(raw_p_values, dtype=float)
    # L5b-F Phase 5 (F-M4a) — dispatch to BH or BY adjustment.
    if method == "BY":
        q_arr = _benjamini_yekutieli_qvalues(p_arr)
    else:
        q_arr = _benjamini_hochberg_qvalues(p_arr)
    rejected = tuple(int(i) for i in np.where(q_arr <= q_threshold)[0])

    return FDRGatingDiagnostics(
        raw_p_values=tuple(raw_p_values),
        q_values=tuple(float(q) for q in q_arr),
        q_threshold=q_threshold,
        n_tests=len(raw_p_values),
        n_rejected=len(rejected),
        rejected_indices=rejected,
        test_labels=tuple(test_labels),
    )


__all__ = [
    "FDRGatingDiagnostics",
    "compute_fdr_gating_for_l5_chain",
]
